### PR TITLE
Adding cockroachdb support

### PR DESCRIPTION
**Pull request by chirino**
This PR changes the generated SQL so that it's also compatible with CockroachDB.
Notable changes:
* use `SELECT to_jsonb("__sr_0".*)`  instead of `SELECT to_jsonb("__sr_0")`
* don't use `json_populate_record`, use the `CAST` and `->>` instead.  For example:

  instead of: `SELECT "t"."full_name", "t"."email" FROM "_sg_input" i, json_populate_record(NULL::users, i.j) t`

  do: `CAST( i.j ->>'full_name' AS character varying), CAST( i.j ->>'email' AS character varying) FROM "_sg_input" i`

This PR also adds an integration test which is only run if you install the cockroachdb executable on your PATH.  It will startup a temporary cockroachdb instance on a random port to test against.  It is stopped and the tmp data files are deleted once the test ends.

### CODE REVIEW

**Comment by dosco** [comment]
I don't have a test to share but I tried with a complex app I have that uses Super Graph and I saw these issues this insert was breaking. Several issues like some minor `:: jsonAS j` others more complex `"_sg_input" i ", " _x_posts RETURNING *` I didn't have the time to suggest fixes right now 

Link to a diff between the original working version and the version generated by your branch. http://www.mergely.com/hNL5rW83/

**Comment by chirino** [comment]
Seems like it failed doing a nested insert..  I added a test case for the to the integration tests and figured out what was wrong.  I think it should work now.  BTW the integration tests can now be run against running DB by setting `SG_POSTGRESQL_TEST_URL` env var like:
`SG_POSTGRESQL_TEST_URL=postgresql://user:pass@localhost:5432/dbname`

Really hope we can build out a good set of integration tests so that issues like this can be caught early.

> I don't have a test to share but I tried with a complex app I have that uses Super Graph and I saw these issues this insert was breaking. Several issues like some minor `:: jsonAS j` others more complex `"_sg_input" i ", " _x_posts RETURNING *` I didn't have the time to suggest fixes right now
> 
> Link to a diff between the original working version and the version generated by your branch. http://www.mergely.com/hNL5rW83/

**Comment by chirino** [comment]
rebased from master and squashed commits.

**Comment by dosco** [comment]
Looking good. I ran the integration tests seems like nested-insert is still work in progress. I do like the integration tests we should make make it also create and delete the database. I'd like to add similar integration tests for Postgres too so this makes it easier to model off. Doing some more testing but I'm aiming to merge it today.

**Pull request merged**
