### PR TITLE
chore: *SuperGraph also implements the graphql.Handler interface so that it can reuse the http handler in the chirino/graphql module.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by dosco** [comment]
Two issues with the PR.

1. The public API function `ServGraphQL` exposes structs from a different library. We will need full control of the structs that our library exposes. One way could be to recreate the structs.

2. I need to think this through while this is cool and obviously useful I'm considering exposing the entire`serv` package (currently internal) via such an API. This would help people integrate the Super Graph service into their app along with all the goodness like authentication, compression, tracing, etc

**Comment by frederikhors** [comment]
@dosco any news on an handler for SuperGraph? I'm trying it as a library for the first time today and I don't know how to start. I will push a simple repo in a few moments.

**Comment by dosco** [comment]
@frederikhors Do you want to embed the whole service or just use GraphQL in some places in your app. If it's the later then you can try this https://supergraph.dev/docs/home#using-it-in-your-own-code. I'm working on the API to include the whole service in your own app. Could you explain the reasoning behind embedding the whole service why not run two services for now?

**Comment by frederikhors** [comment]
I answered here: https://github.com/dosco/super-graph/issues/81.

**Comment by dosco** [comment]
@chirino we now have a `Subscribe` function and the original `GraphQL` function both levering a common Result object which itself can be encoded into the json response. Probably a good time to revisit this pull request. We could expose all of the `serv` package now as a single `ServGraphQL` api there has been a lot of work to move globals into a common struct etc so we could package it into a library.

**Pull request closed without merging**
